default: &default
  adapter: postgresql
  encoding: unicode
  host: meta-db
  username: postgres
  pool: 5

development:
  <<: *default
  database: meta-ms_development


test:
  <<: *default
  database: meta-ms_test